const axios = require('axios');
const API_URL = 'http://104.248.202.152:3000/api/events';

const aprilEvents = [
  {id: "apr_001", day: 14, month: 4, year: 1431, titleBn: "পহেলা বৈশাখ", titleEn: "Pohela Boishakh", type: "cultural", color: "#D4A017", descriptionBn: "বাঙালির প্রাণের উৎসব বাংলা নববর্ষ। প্রতিবছর ১৪ এপ্রিল বাংলা নববর্ষ উদযাপিত হয়। মঙ্গল শোভাযাত্রা, রামনা বটমূলে চৈত্র সংক্রান্তি উৎসব, হলুদ টিপসহ বর্ষবরণ অনুষ্ঠান হয়। বাঙালি সংস্কৃতির অন্যতম বড় উৎসব। সারা বিশ্বে বাঙালিরা এই দিনটি উদযাপন করে। মঙ্গল শোভাযাত্রা ইউনেস্কো কর্তৃক বিশ্ব ঐতিহ্য হিসেবে স্বীকৃত। পহেলা বৈশাখে বাঙালিরা নতুন বছরকে স্বাগত জানায়। পান্তা ইলিশ ও পিঠা খাওয়ার প্রথা আছে। হাটবাজারে বিশেষ আয়োজন থাকে। পহেলা বৈশাখ বাঙালির ঐতিহ্য ও সংস্কৃতির প্রতীক।", descriptionEn: "Bengali New Year, the biggest cultural festival of Bengalis. Celebrated on April 14 every year. Mangal Shobhajatra, Chaitra Sankranti festival at Ramna Park, and New Year celebrations with yellow turbans are held. One of the biggest festivals of Bengali culture. Bengalis all over the world celebrate this day. Mangal Shobhajatra is recognized as a World Heritage by UNESCO. On Pohela Boishakh, Bengalis welcome the new year. There is a tradition of eating Hilsa fish and Pitha. Special arrangements are made in markets. Pohela Boishakh is a symbol of Bengali tradition and culture.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Mongol_Shobhajatra_2017.jpg/640px-Mongol_Shobhajatra_2017.jpg"},
  {id: "apr_002", day: 24, month: 4, year: 0, titleBn: "জাতীয় স্যানিটেশন মাস উদ্বোধন", titleEn: "National Sanitation Month Inauguration", type: "national", color: "#228B22", descriptionBn: "এপ্রিল মাস জাতীয় স্যানিটেশন মাস। ২৪ এপ্রিল মাসের উদ্বোধন হয়। স্বাস্থ্যসম্মত পরিবেশ ও স্যানিটেশন নিশ্চিত করতে এই মাস পালন করা হয়। সরকার ও বেসরকারি প্রতিষ্ঠান এই মাসে বিশেষ কর্মসূচি গ্রহণ করে। স্যানিটেশন ব্যবস্থা উন্নয়নে গুরুত্ব দেওয়া হয়। জনসচেতনতা তৈরি করা হয়। বিভিন্ন কর্মশালা ও সেমিনার অনুষ্ঠিত হয়। স্যানিটেশন মাস স্বাস্থ্য সুরক্ষায় গুরুত্বপূর্ণ ভূমিকা পালন করে।", descriptionEn: "April is National Sanitation Month. The month is inaugurated on April 24. This month is observed to ensure healthy environment and sanitation. Government and private institutions take special programs this month. Importance is given to improving sanitation systems. Public awareness is created. Various workshops and seminars are held. Sanitation Month plays an important role in health protection.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Sanitation.jpg/640px-Sanitation.jpg"},
  {id: "apr_003", day: 29, month: 4, year: 1991, titleBn: "ঘূর্ণিঝড় দুর্গতি ১৯৯১", titleEn: "Cyclone Disaster 1991", type: "historical", color: "#8B0000", descriptionBn: "১৯৯১ সালের ২৯ এপ্রিল বাংলাদেশে ভয়াবহ ঘূর্ণিঝড় আঘাত হায়। এতে প্রায় ১.৪ লাখ মানুষ নিহত হয়। দক্ষিণ-পূর্ব উপকূলের এলাকাগুলো সবচেয়ে বেশি ক্ষতিগ্রস্ত হয়। চট্টগ্রাম, নোয়াখালী, ভোলা ও পটুয়াখালী জেলা ব্যাপক ক্ষতির সম্মুখীন হয়। এটি বাংলাদেশের ইতিহাসে সবচেয়ে ভয়াবহ প্রাকৃতিক দুর্যোগ। এই দিনটি স্মরণে বিশেষ দোয়া ও মিলাদ অনুষ্ঠিত হয়। দুর্গতদের জন্য সাহায্য করা হয়। ঘূর্ণিঝড় দুর্গতি বাংলাদেশের জন্য এক কঠিন স্মৃতি।", descriptionEn: "On April 29, 1991, a devastating cyclone hit Bangladesh. About 1.4 lakh people were killed. The areas of the southeast coast were most damaged. Chittagong, Noakhali, Bhola and Patuakhali districts faced extensive damage. This is the most devastating natural disaster in the history of Bangladesh. Special prayers and milad are held in memory of this day. Help is provided to the victims. Cyclone Disaster 1991 is a difficult memory for Bangladesh.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Cyclone_1991.jpg/640px-Cyclone_1991.jpg"},
  {id: "apr_004", day: 18, month: 4, year: 1936, titleBn: "হুমায়ুন আজাদের জন্মদিন", titleEn: "Humayun Azad's Birthday", type: "person", color: "#1E3A5F", descriptionBn: "প্রখ্যাত লেখক, কবি ও শিক্ষাবিদ হুমায়ুন আজাদের জন্মদিন। তিনি ১৯৩৬ সালের ১৮ এপ্রিল রাজশাহী জেলার গোদাগাড়ী উপজেলায় জন্মগ্রহণ করেন। তার লেখায় মুক্তচিন্তা ও প্রগতিশীলতা ফুটে উঠেছে। তিনি ঢাকা বিশ্ববিদ্যালয়ে দীর্ঘদিন শিক্ষকতা করেন। তার রচনায় সমাজ ও রাজনীতির সমালোচনা ফুটে উঠে। নারী, ছানা, সবার জন্য রক্ত তার অন্যতম বিখ্যাত কাজ। তিনি একুশে পদক ও বাংলা একাডেমি পুরস্কার পান। ২০০৪ সালে তিনি মৃত্যুবরণ করেন। হুমায়ুন আজাদ বাংলা সাহিত্যের অন্যতম প্রগতিশীল লেখক।", descriptionEn: "Birth anniversary of eminent writer, poet and academic Humayun Azad. He was born on April 18, 1936 in Gobindaganj upazila of Rajshahi district. Free thinking and progressiveness are reflected in his writings. He taught at Dhaka University for a long time. Criticism of society and politics is reflected in his writings. Nari, Chhana, Shobar Jonno Rokto are his famous works. He received Ekushey Padak and Bangla Academy Award. He passed away in 2004. Humayun Azad is one of the progressive writers of Bengali literature.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Humayun_Azad.jpg/440px-Humayun_Azad.jpg"},
  {id: "apr_005", day: 24, month: 4, year: 1910, titleBn: "তাজউদ্দীন আহমদের জন্মদিন", titleEn: "Tajuddin Ahmad's Birthday", type: "person", color: "#1E3A5F", descriptionBn: "বাংলাদেশের প্রথম প্রধানমন্ত্রী তাজউদ্দীন আহমদের জন্মদিন। তিনি ১৯১০ সালের ২৪ এপ্রিল গাজীপুর জেলার কাপাসিয়া উপজেলায় জন্মগ্রহণ করেন। তিনি মুক্তিযুদ্ধের সময় অস্থায়ী সরকারের প্রধানমন্ত্রী ছিলেন। তিনি মুজিবনগর সরকার গঠনে গুরুত্বপূর্ণ ভূমিকা পালন করেন। ১৯৭৫ সালের ৩ নভেম্বর জেল হত্যায় তিনি শহীদ হন। বাংলাদেশ সরকার তাকে জাতীয় নেতা হিসেবে স্বীকৃতি দিয়েছে। তার জন্মদিন প্রতিবছর যথাযথভাবে পালিত হয়।", descriptionEn: "Birth anniversary of Bangladesh's first Prime Minister Tajuddin Ahmad. He was born on April 24, 1910 in Kapasia upazila of Gazipur district. He was the Prime Minister of the interim government during the liberation war. He played an important role in forming the Mujibnagar government. He was martyred in the jail killing on November 3, 1975. The Government of Bangladesh has recognized him as a national leader. His birthday is celebrated every year with due respect.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Tajuddin_Ahmad.jpg/440px-Tajuddin_Ahmad.jpg"}
];

async function addEvents() {
  for (const event of aprilEvents) {
    try {
      const response = await axios.post(API_URL, event);
      console.log(`Added: ${event.titleEn}`);
    } catch (error) {
      console.error(`Error adding ${event.titleEn}:`, error.response ? error.response.data : error.message);
    }
  }
  console.log('All April events added successfully!');
}

addEvents();
