const axios = require('axios');
const API_URL = 'http://104.248.202.152:3000/api/events';

const decemberEvents = [
  {id: "dec_001", day: 1, month: 12, year: 0, titleBn: "বিজয় দিবস", titleEn: "Victory Day", type: "historical", color: "#1E3A5F", descriptionBn: "১৬ ডিসেম্বর বিজয় দিবস। ১৯৭১ সালের ১৬ ডিসেম্বর বাংলাদেশ মুক্তিযুদ্ধে বিজয় অর্জন করে। পাকিস্তানি বাহিনী আত্মসমর্পণ করে। এই দিনটি বিজয় দিবস হিসেবে পালিত হয়। সরকারি ছুটি থাকে। জাতীয় প্যারেড ও সাংস্কৃতিক অনুষ্ঠান হয়। টেলিভিশন ও রেডিওতে বিশেষ অনুষ্ঠান প্রচার করা হয়। বিজয় দিবস বাংলাদেশের সবচেয়ে গুরুত্বপূর্ণ জাতীয় দিবস।", descriptionEn: "December 16 is Victory Day. Bangladesh achieved victory in the liberation war on December 16, 1971. Pakistani forces surrendered. This day is celebrated as Victory Day. There is a government holiday. National parade and cultural events are held. Special programs are broadcast on television and radio. Victory Day is the most important national day of Bangladesh.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Victory_Day_Bangladesh.jpg/640px-Victory_Day_Bangladesh.jpg"},
  {id: "dec_002", day: 16, month: 12, year: 1971, titleBn: "বিজয় দিবস (ঐতিহাসিক)", titleEn: "Victory Day (Historic)", type: "historical", color: "#1E3A5F", descriptionBn: "১৯৭১ সালের ১৬ ডিসেম্বর বাংলাদেশের মুক্তিযুদ্ধের বিজয় দিবস। ঢাকার সোহরাওয়ার্দী উদ্যানে পাকিস্তানি বাহিনী আত্মসমর্পণ করে। জেনারেল জে এফ আর জ্যাকব বিজয় নিশান গ্রহণ করেন। এই দিনটি বাংলাদেশের ইতিহাসে এক গৌরবের দিন। বাঙালি জাতি স্বাধীনতা অর্জন করে। বিজয় দিবস বাঙালির স্বাধীনতার প্রতীক।", descriptionEn: "December 16, 1971 is the victory day of Bangladesh's liberation war. Pakistani forces surrendered at Suhrawardy Udyan in Dhaka. General J F R Jacob received the surrender document. This day is a day of pride in the history of Bangladesh. Bengali nation achieved independence. Victory Day is a symbol of Bengali independence.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Surrender_Ceremony_1971.jpg/640px-Surrender_Ceremony_1971.jpg"},
  {id: "dec_003", day: 16, month: 12, year: 0, titleBn: "বিজয় দিবস (বার্ষিক)", titleEn: "Victory Day (Annual)", type: "national", color: "#1E3A5F", descriptionBn: "১৬ ডিসেম্বর বিজয় দিবস বার্ষিক পালন। প্রতিবছর এই দিনে জাতীয় প্যারেড ও সাংস্কৃতিক অনুষ্ঠান হয়। সরকারি ছুটি থাকে। সারা দেশে বিভিন্ন অনুষ্ঠানের আয়োজন করা হয়। জাতীয় স্মৃতিসৌধে ফুল দিয়ে শহীদদের প্রতি শ্রদ্ধা জানানো হয়। টেলিভিশন ও রেডিওতে বিশেষ অনুষ্ঠান প্রচার করা হয়। বিজয় দিবস বাঙালির গৌরবের দিন।", descriptionEn: "December 16 Victory Day annual celebration. Every year on this day, national parade and cultural events are held. There is a government holiday. Various events are organized across the country. Martyrs are honored by offering flowers at the National Memorial. Special programs are broadcast on television and radio. Victory Day is a day of pride for Bengalis.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Victory_Day_Parade.jpg/640px-Victory_Day_Parade.jpg"},
  {id: "dec_004", day: 25, month: 12, year: 0, titleBn: "বড়দিন", titleEn: "Christmas Day", type: "religious", color: "#C41E3A", descriptionBn: "২৫ ডিসেম্বর বড়দিন। খ্রিস্টান সম্প্রদায়ের সবচেয়ে বড় ধর্মীয় উৎসব। যিশু খ্রিস্টের জন্মদিন হিসেবে এই দিনটি পালিত হয়। বাংলাদেশে খ্রিস্টান সম্প্রদায় এই দিনটি যথাযথভাবে পালন করে। গির্জায় বিশেষ প্রার্থনা ও উপাসনা করা হয়। খ্রিস্টান সম্প্রদায়ের ঘরে আনন্দ উৎসব হয়। বড়দিন খ্রিস্টান সম্প্রদায়ের জন্য এক আনন্দের দিন।", descriptionEn: "December 25 is Christmas Day. The biggest religious festival of the Christian community. This day is celebrated as the birthday of Jesus Christ. The Christian community in Bangladesh celebrates this day with due respect. Special prayers and worship are held in churches. Joyful celebrations are held in Christian homes. Christmas is a day of joy for the Christian community.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Christmas_Day.jpg/640px-Christmas_Day.jpg"},
  {id: "dec_005", day: 31, month: 12, year: 0, titleBn: "বিদায় বর্ষ", titleEn: "Old Year's Eve", type: "cultural", color: "#D4A017", descriptionBn: "৩১ ডিসেম্বর বিদায় বর্ষ। বছরের শেষ দিনে বিদায় বর্ষ উদযাপিত হয়। নতুন বছরকে স্বাগত জানানোর প্রস্তুতি নেওয়া হয়। বিভিন্ন সাংস্কৃতিক অনুষ্ঠান হয়। রাতে আতশবাজি ও আনন্দ উৎসব হয়। বিদায় বর্ষ বাঙালি সংস্কৃতির অংশ।", descriptionEn: "December 31 is Old Year's Eve. The end of the year is celebrated as Old Year's Eve. Preparations are made to welcome the new year. Various cultural events are held. Fireworks and celebrations take place at night. Old Year's Eve is part of Bengali culture.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/New_Year_Eve.jpg/640px-New_Year_Eve.jpg"}
];

async function addEvents() {
  for (const event of decemberEvents) {
    try {
      const response = await axios.post(API_URL, event);
      console.log(`Added: ${event.titleEn}`);
    } catch (error) {
      console.error(`Error adding ${event.titleEn}:`, error.response ? error.response.data : error.message);
    }
  }
  console.log('All December events added successfully!');
}

addEvents();
