const axios = require('axios');
const API_URL = 'http://104.248.202.152:3000/api/events';

const marchEvents = [
  {id: "mar_001", day: 7, month: 3, year: 1971, titleBn: "ঐতিহাসিক ৭ই মার্চের ভাষণ", titleEn: "Historic 7th March Speech", type: "historical", color: "#C41E3A", descriptionBn: "১৯৭১ সালের ৭ই মার্চ বঙ্গবন্ধু শেখ মুজিবুর রহমানের ঐতিহাসিক ভাষণ। ঢাকার রেসকোর্স ময়দানে (বর্তমান সোহরাওয়ার্দী উদ্যান) দেওয়া এই ভাষণ মুক্তিযুদ্ধের অনুপ্রেরণা ছিল। বঙ্গবন্ধু এই ভাষণে স্বাধীনতার ডাক দেন। তিনি বলেন 'এবারের সংগ্রাম আমাদের মুক্তির সংগ্রাম, এবারের সংগ্রাম স্বাধীনতার সংগ্রাম'। এই ভাষণ বাঙালিকে মুক্তিযুদ্ধের জন্য প্রস্তুত করে। ২০১৭ সালে ইউনেস্কো এই ভাষণকে বিশ্ব ঐতিহ্য হিসেবে স্বীকৃতি দেয়। এটি বাংলাদেশের জন্য এক গৌরবের বিষয়। ৭ই মার্চ ঐতিহাসিক দিন হিসেবে পালিত হয়। বিভিন্ন অনুষ্ঠানের আয়োজন করা হয়। ভাষণের রেকর্ডিং প্রচার করা হয়।", descriptionEn: "The historic March 7 speech by Bangabandhu Sheikh Mujibur Rahman in 1971. This speech at the Race Course Maidan (now Suhrawardy Udyan) in Dhaka was the inspiration for the liberation war. Bangabandhu called for independence in this speech. He said 'This time the struggle is for our liberation, this time the struggle is for independence'. This speech prepared Bengalis for the liberation war. In 2017, UNESCO recognized this speech as a World Heritage. This is a matter of pride for Bangladesh. March 7 is celebrated as a historic day. Various events are organized. The recording of the speech is broadcast.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/7th_March_Speech_of_Bangabandhu.jpg/440px-7th_March_Speech_of_Bangabandhu.jpg"},
  {id: "mar_002", day: 8, month: 3, year: 0, titleBn: "আন্তর্জাতিক নারী দিবস", titleEn: "International Women's Day", type: "national", color: "#C41E3A", descriptionBn: "৮ মার্চ আন্তর্জাতিক নারী দিবস। নারীদের অধিকার ও সমতার জন্য এই দিনটি পালিত হয়। ১৯০৮ সাল থেকে এই দিনটি পালিত হচ্ছে। জাতিসংঘ ১৯৭৫ সালে ৮ মার্চকে আন্তর্জাতিক নারী দিবস হিসেবে ঘোষণা করে। বিশ্বব্যাপী নারীদের অধিকার আদায়ের জন্য এই দিনটি গুরুত্বপূর্ণ। বাংলাদেশে নারী অধিকার নিয়ে আলোচনা সভা অনুষ্ঠিত হয়। নারীদের সম্মাননা ও পুরস্কার দেওয়া হয়। সরকারি ও বেসরকারি প্রতিষ্ঠানে বিশেষ অনুষ্ঠান হয়। নারী নেত্রীদের অবদান তুলে ধরা হয়। টেলিভিশন ও রেডিওতে বিশেষ অনুষ্ঠান প্রচার করা হয়। আন্তর্জাতিক নারী দিবস নারী ক্ষমতায়নের প্রতীক।", descriptionEn: "March 8 is International Women's Day. This day is observed for women's rights and equality. This day has been celebrated since 1908. The United Nations declared March 8 as International Women's Day in 1975. This day is important for securing women's rights worldwide. Discussion sessions on women's rights are held in Bangladesh. Women are honored and awarded. Special events are held in government and private institutions. The contributions of women leaders are highlighted. Special programs are broadcast on television and radio. International Women's Day is a symbol of women's empowerment.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/International_Women%27s_Day_2021_-_Google_Doodle.jpg/640px-International_Women%27s_Day_2021_-_Google_Doodle.jpg"},
  {id: "mar_003", day: 17, month: 3, year: 1920, titleBn: "বঙ্গবন্ধুর জন্মদিন", titleEn: "Bangabandhu's Birthday", type: "person", color: "#C41E3A", descriptionBn: "জাতির পিতা বঙ্গবন্ধু শেখ মুজিবুর রহমানের জন্মদিন ও জাতীয় শিশু দিবস। তিনি ১৯২০ সালের ১৭ মার্চ গোপালগঞ্জের টুঙ্গিপাড়ায় জন্মগ্রহণ করেন। তার পিতার নাম শেখ লুৎফর রহমান ও মাতার নাম সায়েরা খাতুন। তিনি বাংলাদেশের স্বাধীনতা আন্দোলনের প্রধান নেতা ছিলেন। তিনি ১৯৭১ সালে বাংলাদেশের স্বাধীনতার ঘোষণা দেন। তিনি বাংলাদেশের প্রথম রাষ্ট্রপতি ছিলেন। ১৯৭৫ সালের ১৫ আগস্ট তিনি শহীদ হন। বঙ্গবন্ধুর জন্মদিন জাতীয় শিশু দিবস হিসেবেও পালিত হয়। সরকারি ছুটি থাকে। বিভিন্ন অনুষ্ঠানের আয়োজন করা হয়। শিশুদের জন্য বিশেষ আয়োজন করা হয়। টুঙ্গিপাড়ায় বিশেষ অনুষ্ঠান হয়।", descriptionEn: "Birth anniversary of Father of the Nation Bangabandhu Sheikh Mujibur Rahman and National Children's Day. He was born on March 17, 1920 at Tungipara, Gopalganj. His father's name was Sheikh Lutfur Rahman and mother's name was Sayera Khatun. He was the main leader of Bangladesh's independence movement. He declared the independence of Bangladesh in 1971. He was the first President of Bangladesh. He was martyred on August 15, 1975. Bangabandhu's birthday is also celebrated as National Children's Day. There is a government holiday. Various events are organized. Special arrangements are made for children. Special events are held at Tungipara.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Sheikh_Mujibur_Rahman_in_1972.jpg/440px-Sheikh_Mujibur_Rahman_in_1972.jpg"},
  {id: "mar_004", day: 23, month: 3, year: 1918, titleBn: "মুজিবুর রহমানের জন্মদিন", titleEn: "Muzibur Rahman's Birthday", type: "person", color: "#1E3A5F", descriptionBn: "জাতীয় নেতা মুজিবুর রহমানের জন্মদিন। তিনি ১৯১৮ সালের ২৩ মার্চ ফরিদপুর জেলার আমবাড়িয়া গ্রামে জন্মগ্রহণ করেন। তিনি বাংলাদেশের স্বাধীনতা আন্দোলনের অন্যতম নেতা ছিলেন। তিনি আওয়ামী লীগের প্রতিষ্ঠাতা সদস্য ছিলেন। তিনি মুজিবনগর সরকারের অন্যতম সদস্য ছিলেন। ১৯৭৫ সালের ৩ নভেম্বর জেল হত্যায় তিনি শহীদ হন। বাংলাদেশ সরকার তাকে জাতীয় নেতা হিসেবে স্বীকৃতি দিয়েছে। তার জন্মদিন প্রতিবছর যথাযথভাবে পালিত হয়।", descriptionEn: "Birth anniversary of national leader Muzibur Rahman. He was born on March 23, 1918 in Ambiaya village of Faridpur district. He was one of the leaders of Bangladesh's independence movement. He was a founding member of Awami League. He was one of the members of Mujibnagar government. He was martyred in the jail killing on November 3, 1975. The Government of Bangladesh has recognized him as a national leader. His birthday is celebrated every year with due respect.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Muzibur_Rahman.jpg/440px-Muzibur_Rahman.jpg"},
  {id: "mar_005", day: 25, month: 3, year: 1971, titleBn: "গণহত্যা দিবস", titleEn: "Genocide Day", type: "historical", color: "#8B0000", descriptionBn: "১৯৭১ সালের ২৫ মার্চ কালরাতে পাকিস্তানি বাহিনী নিরস্ত্র বাঙালিদের ওপর হামলা শুরু করে। অপারেশন সার্চলাইটের মাধ্যমে গণহত্যা শুরু হয়। ঢাকায় হাজার হাজার মানুষ নিহত হয়। বঙ্গবন্ধুকে গ্রেফতার করে পশ্চিম পাকিস্তানে নিয়ে যাওয়া হয়। এই দিনটি গণহত্যা দিবস হিসেবে পালিত হয়। শহীদদের স্মরণে বিশেষ দোয়া ও মিলাদ অনুষ্ঠিত হয়। সরকারি ছুটি থাকে। বিভিন্ন অনুষ্ঠানের আয়োজন করা হয়। গণহত্যা দিবস বাংলাদেশের ইতিহাসে এক কালো অধ্যায়।", descriptionEn: "On the night of March 25, 1971, Pakistani forces launched attacks on unarmed Bengalis. The genocide began through Operation Searchlight. Thousands of people were killed in Dhaka. Bangabandhu was arrested and taken to West Pakistan. This day is observed as Genocide Day. Special prayers and milad are held in memory of the martyrs. There is a government holiday. Various events are organized. Genocide Day is a dark chapter in the history of Bangladesh.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Shaheed_Minar_Dhaka.jpg/640px-Shaheed_Minar_Dhaka.jpg"},
  {id: "mar_006", day: 26, month: 3, year: 1971, titleBn: "স্বাধীনতা দিবস", titleEn: "Independence Day", type: "historical", color: "#1E3A5F", descriptionBn: "১৯৭১ সালের ২৬ মার্চ বাংলাদেশের স্বাধীনতা সংগ্রামের সূচনা দিবস। বঙ্গবন্ধু শেখ মুজিবুর রহমান ২৫ মার্চ রাতে স্বাধীনতার ঘোষণা দেন। ২৬ মার্চ থেকে আনুষ্ঠানিকভাবে মুক্তিযুদ্ধ শুরু হয়। এই দিনটি স্বাধীনতা দিবস হিসেবে পালিত হয়। সরকারি ছুটি থাকে। জাতীয় পতাকা উত্তোলন করা হয়। প্যারেড ও সাংস্কৃতিক অনুষ্ঠান হয়। টেলিভিশন ও রেডিওতে বিশেষ অনুষ্ঠান প্রচার করা হয়। স্বাধীনতা দিবস বাংলাদেশের সবচেয়ে গুরুত্বপূর্ণ জাতীয় দিবস।", descriptionEn: "The start of Bangladesh's struggle for independence on March 26, 1971. Bangabandhu Sheikh Mujibur Rahman declared independence on the night of March 25. The liberation war officially began on March 26. This day is celebrated as Independence Day. There is a government holiday. The national flag is hoisted. Parades and cultural events are held. Special programs are broadcast on television and radio. Independence Day is the most important national day of Bangladesh.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Bangladesh.svg/440px-Flag_of_Bangladesh.svg.png"},
  {id: "mar_007", day: 26, month: 3, year: 0, titleBn: "স্বাধীনতা দিবস (বার্ষিক)", titleEn: "Independence Day (Annual)", type: "national", color: "#1E3A5F", descriptionBn: "২৬ মার্চ স্বাধীনতা দিবস বার্ষিক পালন। প্রতিবছর এই দিনে জাতীয় পতাকা উত্তোলন, প্যারেড ও সাংস্কৃতিক অনুষ্ঠান হয়। সরকারি ছুটি থাকে। সারা দেশে বিভিন্ন অনুষ্ঠানের আয়োজন করা হয়। জাতীয় স্মৃতিসৌধে ফুল দিয়ে শহীদদের প্রতি শ্রদ্ধা জানানো হয়। টেলিভিশন ও রেডিওতে বিশেষ অনুষ্ঠান প্রচার করা হয়। স্বাধীনতা দিবস বাঙালির গৌরবের দিন।", descriptionEn: "March 26 Independence Day annual celebration. Every year on this day, national flag hoisting, parades, and cultural events are held. There is a government holiday. Various events are organized across the country. Martyrs are honored by offering flowers at the National Memorial. Special programs are broadcast on television and radio. Independence Day is a day of pride for Bengalis.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Bangladesh.svg/440px-Flag_of_Bangladesh.svg.png"},
  {id: "mar_008", day: 30, month: 3, year: 0, titleBn: "জাতীয় শিশু দিবস", titleEn: "National Children's Day", type: "national", color: "#D4A017", descriptionBn: "৩০ মার্চ জাতীয় শিশু দিবস। শিশুদের অধিকার ও উন্নয়নের জন্য এই দিনটি পালিত হয়। বঙ্গবন্ধু শেখ মুজিবুর রহমান শিশুদের ভালোবাসতেন। তার জন্মদিন জাতীয় শিশু দিবস হিসেবে পালিত হয়। শিশুদের জন্য বিশেষ অনুষ্ঠানের আয়োজন করা হয়। শিশুদের অধিকার নিয়ে আলোচনা সভা হয়। শিশুদের পুরস্কার ও সম্মাননা দেওয়া হয়। টেলিভিশন ও রেডিওতে শিশুদের জন্য বিশেষ অনুষ্ঠান প্রচার করা হয়। জাতীয় শিশু দিবস শিশুদের অধিকার আদায়ের প্রতীক।", descriptionEn: "March 30 is National Children's Day. This day is observed for children's rights and development. Bangabandhu Sheikh Mujibur Rahman loved children. His birthday is celebrated as National Children's Day. Special events are organized for children. Discussion sessions on children's rights are held. Children are awarded and honored. Special programs for children are broadcast on television and radio. National Children's Day is a symbol of securing children's rights.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Children_Day.jpg/640px-Children_Day.jpg"}
];

async function addEvents() {
  for (const event of marchEvents) {
    try {
      const response = await axios.post(API_URL, event);
      console.log(`Added: ${event.titleEn}`);
    } catch (error) {
      console.error(`Error adding ${event.titleEn}:`, error.response ? error.response.data : error.message);
    }
  }
  console.log('All March events added successfully!');
}

addEvents();
