const axios = require('axios');
const API_URL = 'http://104.248.202.152:3000/api/events';

const octoberEvents = [
  {id: "oct_001", day: 1, month: 10, year: 0, titleBn: "জাতীয় নিরাপদ মাতৃত্ব দিবস", titleEn: "National Safe Motherhood Day", type: "national", color: "#D4A017", descriptionBn: "১ অক্টোবর জাতীয় নিরাপদ মাতৃত্ব দিবস। মাতৃত্বকালীন স্বাস্থ্য সুরক্ষায় জনসচেতনতা তৈরির জন্য এই দিনটি পালিত হয়। মা ও শিশুদের স্বাস্থ্য সুরক্ষায় গুরুত্ব দেওয়া হয়। সরকারি ও বেসরকারি প্রতিষ্ঠান এই দিনে বিশেষ কর্মসূচি গ্রহণ করে। মাতৃত্ব স্বাস্থ্য নিয়ে সেমিনার ও আলোচনা সভা হয়। জাতীয় নিরাপদ মাতৃত্ব দিবস মা ও শিশুদের স্বাস্থ্য সুরক্ষায় গুরুত্বপূর্ণ ভূমিকা পালন করে।", descriptionEn: "October 1 is National Safe Motherhood Day. This day is observed to create public awareness for maternal health protection. Importance is given to the health protection of mothers and children. Government and private institutions take special programs on this day. Seminars and discussion sessions on maternal health are held. National Safe Motherhood Day plays an important role in the health protection of mothers and children.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Mother_and_child.jpg/640px-Mother_and_child.jpg"},
  {id: "oct_002", day: 10, month: 10, year: 0, titleBn: "বিশ্ব মানসিক স্বাস্থ্য দিবস", titleEn: "World Mental Health Day", type: "national", color: "#228B22", descriptionBn: "১০ অক্টোবর বিশ্ব মানসিক স্বাস্থ্য দিবস। মানসিক স্বাস্থ্য সম্পর্কে জনসচেতনতা তৈরির জন্য এই দিনটি পালিত হয়। জাতিসংঘ ১৯৯২ সালে ১০ অক্টোবরকে বিশ্ব মানসিক স্বাস্থ্য দিবস হিসেবে ঘোষণা করে। বিশ্বব্যাপী এই দিনটি পালিত হয়। বাংলাদেশে বিশেষ কর্মসূচি গ্রহণ করা হয়। মানসিক স্বাস্থ্য নিয়ে সেমিনার ও আলোচনা সভা হয়। বিশ্ব মানসিক স্বাস্থ্য দিবস মানসিক স্বাস্থ্য সুরক্ষায় গুরুত্বপূর্ণ ভূমিকা পালন করে।", descriptionEn: "October 10 is World Mental Health Day. This day is observed to create public awareness about mental health. The United Nations declared October 10 as World Mental Health Day in 1992. This day is celebrated worldwide. Special programs are taken in Bangladesh. Seminars and discussion sessions on mental health are held. World Mental Health Day plays an important role in mental health protection.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Mental_Health_Day.jpg/640px-Mental_Health_Day.jpg"},
  {id: "oct_003", day: 16, month: 10, year: 0, titleBn: "বিশ্ব খাদ্য দিবস", titleEn: "World Food Day", type: "national", color: "#228B22", descriptionBn: "১৬ অক্টোবর বিশ্ব খাদ্য দিবস। খাদ্য নিরাপত্তা ও পুষ্টি নিয়ে জনসচেতনতা তৈরির জন্য এই দিনটি পালিত হয়। জাতিসংঘ ১৯৭৯ সালে ১৬ অক্টোবরকে বিশ্ব খাদ্য দিবস হিসেবে ঘোষণা করে। বিশ্বব্যাপী এই দিনটি পালিত হয়। বাংলাদেশে বিশেষ কর্মসূচি গ্রহণ করা হয়। খাদ্য নিরাপত্তা নিয়ে সেমিনার ও আলোচনা সভা হয়। বিশ্ব খাদ্য দিবস খাদ্য নিরাপত্তায় গুরুত্বপূর্ণ ভূমিকা পালন করে।", descriptionEn: "October 16 is World Food Day. This day is observed to create public awareness about food security and nutrition. The United Nations declared October 16 as World Food Day in 1979. This day is celebrated worldwide. Special programs are taken in Bangladesh. Seminars and discussion sessions on food security are held. World Food Day plays an important role in food security.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/World_Food_Day.jpg/640px-World_Food_Day.jpg"},
  {id: "oct_004", day: 24, month: 10, year: 0, titleBn: "জাতিসংঘ দিবস", titleEn: "United Nations Day", type: "national", color: "#1E3A5F", descriptionBn: "২৪ অক্টোবর জাতিসংঘ দিবস। জাতিসংঘ প্রতিষ্ঠার স্মরণে এই দিনটি পালিত হয়। ১৯৪৫ সালের ২৪ অক্টোবর জাতিসংঘ প্রতিষ্ঠিত হয়। বিশ্বব্যাপী এই দিনটি পালিত হয়। বাংলাদেশে বিশেষ অনুষ্ঠানের আয়োজন করা হয়। জাতিসংঘের কার্যক্রম নিয়ে আলোচনা সভা হয়। জাতিসংঘ দিবস শান্তি ও উন্নয়নের প্রতীক।", descriptionEn: "October 24 is United Nations Day. This day is observed in memory of the establishment of the United Nations. The United Nations was established on October 24, 1945. This day is celebrated worldwide. Special events are organized in Bangladesh. Discussion sessions on UN activities are held. United Nations Day is a symbol of peace and development.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/United_Nations_Day.jpg/640px-United_Nations_Day.jpg"}
];

async function addEvents() {
  for (const event of octoberEvents) {
    try {
      const response = await axios.post(API_URL, event);
      console.log(`Added: ${event.titleEn}`);
    } catch (error) {
      console.error(`Error adding ${event.titleEn}:`, error.response ? error.response.data : error.message);
    }
  }
  console.log('All October events added successfully!');
}

addEvents();
